api:
  insecure: false
  dashboard: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  web:
    address: :80

  websecure:
    address: :443
  flower:
    address: :5555
  prometheus:
    address: :9090
  grafana:
    address: :3000
  metrics:
    address: ":9191"
providers:
  docker:
    exposedByDefault: false
  file: # Reads all files located in /etc/traefik/*
    watch: true
    directory: "/etc/traefik/"

certificatesResolvers: # Certs handler/resolver
  letsencrypt:
    acme:
      storage: "/etc/traefik/acme/acme.json"
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      tlsChallenge: true
      # dnsChallenge:
      #   provider: cloudflare
      #   resolvers:
      #     - "1.1.1.1:53"
      #     - "8.8.8.8:53"

log:
  filePath: "/var/log/traefik/applog.log"
  level: INFO

accessLog:
  filePath: "/var/log/traefik/access.log"
  # format: json
  # filters:
  #   statusCodes:
  #     - "200"
  #     - "300-302"
  #   retryAttempts: true
  #   minDuration: "10ms"
  fields:
    defaultMode: keep
    # names:
    #   ClientUsername: drop
    headers:
      defaultMode: keep
      names:
          User-Agent: keep
          Authorization: drop
          Content-Type: keep

pilot:
    token: ""
